# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cat',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cat',
            field=models.ManyToManyField(to='portfolios.Category'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to=portfolios.models.upload_location),
        ),
    ]
