# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20170315_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cat',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolios.Category'),
        ),
    ]
