# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20170315_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAddInfo',
        ),
    ]
