# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20170322_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
